{% set name = "tsfresh" %}
{% set version = "0.20.0" %}
{% set sha256 = "1d9a0f06cf791167239c7fe7e32e3a46653f97a9b27937090273b4507ec4709c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >=3.8
    - setuptools
    - requests >=2.9.1
    - numpy >=1.15.1, <1.24
    - pandas >=0.25.0
    - scipy >=1.2.0
    - statsmodels >=0.13
    - patsy >=0.4.1
    - scikit-learn >=0.22.0
    - tqdm >=4.10.0
    - dask[dataframe] >=2.9.0
    - distributed >=2.11.0
    - stumpy >=1.7.2
    - cloudpickle

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tsfresh

about:
  home: http://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic extraction of relevant features from time series

  doc_url: http://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - kempa-liehr
    - MaxBenChrist
    - nils-braun
    - xhochy
