{% set name = "tsfresh" %}
{% set version = "0.20.0" %}
{% set sha256 = "1d9a0f06cf791167239c7fe7e32e3a46653f97a9b27937090273b4507ec4709c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >=3.6
    - setuptools
    - requests >=2.9.1
    - numpy >=1.12.1
    - pandas >=0.20.3,!=0.24.*
    - scipy >=1.2.0
    - statsmodels >=0.8.0
    - patsy >=0.4.1
    - scikit-learn >=0.19.0
    - tqdm >=4.10.0
    - dask >=0.15.2
    - distributed >=1.18.3
    - matrixprofile >=1.1.10,<2.0.0
    - stumpy >=1.7.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tsfresh

about:
  home: http://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic extraction of relevant features from time series

  doc_url: http://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - kempa-liehr
    - MaxBenChrist
    - nils-braun
    - xhochy
